# Generated by Django 4.2.10 on 2024-11-27 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_image_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='image',
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='blog.review'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
